<?php


namespace Angel\Raffle\Model\Product\Type;

use Angel\Raffle\Model\Product\Attribute\Source\RaffleStatus;

class Raffle extends \Magento\Catalog\Model\Product\Type\Virtual
{

    const TYPE_ID = 'raffle';

    /**
     * {@inheritdoc}
     */
    public function deleteTypeSpecificData(\Magento\Catalog\Model\Product $product)
    {
        // method intentionally empty
    }

    public function isSalable($product)
    {
        if ($product->getRaffleStatus() == RaffleStatus::PROCESSING) {
            return parent::isSalable($product); // TODO: Change the autogenerated stub
        }
        return false;
    }
}
